Traceback (most recent call last):
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/spr/Documentos/Docencia/AO/twid/lib64/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Conversi√≥n a coordenadas ecuatoriales
sin_d = np.sin(eps) * np.sin(lon)
dec = Angle(np.arcsin(sin_d))
cos_d = np.cos(dec)

cos_a = np.cos(lon) / cos_d
sin_a = np.cos(eps) * np.sin(lon) / cos_d
ra = Angle(np.arctan2(sin_a, cos_a))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-8-c1cbc414cbdf>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Conversi√≥n a coordenadas ecuatoriales[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0msin_d[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0msin[0m[0;34m([0m[0meps[0m[0;34m)[0m [0;34m*[0m [0mnp[0m[0;34m.[0m[0msin[0m[0;34m([0m[0mlon[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mdec[0m [0;34m=[0m [0mAngle[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0marcsin[0m[0;34m([0m[0msin_d[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mcos_d[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mcos[0m[0;34m([0m[0mdec[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'eps' is not defined
NameError: name 'eps' is not defined

